### ISSUE TITLE
SIRD crashes with Not a HASH reference error 

### ISSUE THREAD

**Issue by wolfff** [mumpitzstuff/fhem-SIRD#1]
In my set-up I am using SIRD with a Hama DIT2010MBT running ir-mmi-FS2026-0500-0410_V2.11.19c.Ex70731-1A12

After updating to newest SIRD I see perl crashing with " Not a HASH reference error " in line 1973

I hacked a small correction in 
https://github.com/mumpitzstuff/fhem-SIRD/blob/45120f5f14fbfb211f15f682522cb2dc3b0ee0a8/FHEM/17_SIRD.pm#L1973

to 

```
if (exists($item->{key}) && 
   exists($item->{field}) && 
   ( UNIVERSAL::isa( $item->{field}, 'HASH' )) && 
   !ref($item->{field}->{c8_array}))
```
to be on the safe side if $item->{field} is not a hash. 
Hope it helps (and that I interpreted the logic correctly)

Cheers,

Florian.

**Comment by mumpitzstuff** [comment]
This bugfix will prevent the error message but the function does not work anyway. Could you activate verbose 5 and send me the content of $item please? You can find it within the logfile.
Don't forget the remove the verbose level again, because you will get a lot of data.

**Comment by wolfff** [comment]
The issue is caused by changes in the response to .../fsapi/LIST_GET_NEXT/netRemote.nav.presets/-1?pin=
due to the updated firmware.

Old fw respose looks like:

```
<fsapiResponse>
<status>FS_OK</status>
<item key="0">
<field name="name"><c8_array>Radio Hamburg   </c8_array></field>
</item>
...
```

new fw response contains (unused?) additional information:

```
<fsapiResponse>
<status>FS_OK</status>
<item key="0">
<field name="name"><c8_array>Radio Hamburg   </c8_array></field>
<field name="type"><c8_array></c8_array></field>
</item>
...
```

**Comment by mumpitzstuff** [comment]
field seems to be an array with the new firmware. I will fix the problem.

**Comment by mumpitzstuff** [comment]
```
  if (exists($item->{key}) && exists($item->{field}) && (scalar(@{forcearray($item->{field})}) >= 1))
  {
    foreach my $field (@{forcearray($item->{field})})
    {
      if (exists($field->{name}) && ('name' eq $field->{name}) && !ref($field->{c8_array}))
      {
        $_ = $field->{c8_array};
        $_ =~ s/(?:\:|,)//g;

        $presets .= ',' if ('' ne $presets);
        $presets .= $item->{key}.':'.$_;
      }
    }
  }
```
This should fix your problem.

**Comment by wolfff** [comment]
Yes, I can confirm that with this patch the previous and new firmware of Hama DIT2010MBT works as expected (dabpreset lists are retreived from device and shown in FHEM)

[fhem-17_sird_patch_new_firwware.zip](https://github.com/mumpitzstuff/fhem-SIRD/files/2032760/fhem-17_sird_patch_new_firwware.zip)

Thanks for the fix.

**Comment by mumpitzstuff** [comment]
7e6f5b8129ac398e4d0d56c8187de08fda2c9b49
